<?php

/*
 * This file is part of the dinSymfonyExtraPlugin package.
 * (c) DineCat, 2010 http://dinecat.com/
 * 
 * For the full copyright and license information, please view the LICENSE file,
 * that was distributed with this package, or see http://www.dinecat.com/din/license.html
 */

/**
 * Routing config handler
 * 
 * @package     dinSymfonyExtraPlugin.lib.config
 * @signed      5
 * @signer      relo_san
 * @author      relo_san [http://relo-san.com/]
 * @since       january 3, 2010
 * @version     SVN: $Id$
 */
class dinRoutingConfigHandler extends sfRoutingConfigHandler
{

    /**
     * Executes this configuration handler
     * 
     * @param   array   $configFiles    An array of absolute filesystem path to a configuration file
     * @return  string  Data to be written to a cache file
     * @author  relo_san
     * @since   january 3, 2010
     * @see     sfRoutingConfigHandler::execute()
     */
    public function execute( $configFiles )
    {

        $options = $this->getOptions();
        unset( $options['cache'] );

        $data = array();
        $modules = sfConfig::get( 'sf_enabled_modules' );
        foreach ( $this->parse( $configFiles ) as $name => $routeConfig )
        {
            $r = new ReflectionClass( $routeConfig[0] );
            $routes = $r->newInstanceArgs( $routeConfig[1] );

            if ( $routes instanceof sfRouteCollection )
            {
                $collOptions = $routes->getOptions();
                if ( isset( $collOptions['module'] ) && !in_array( $collOptions['module'], $modules ) )
                {
                    continue;
                }
            }
            else
            {
                $routes = array( $name => $routes );
            }

            foreach ( sfPatternRouting::flattenRoutes( $routes ) as $name => $route )
            {
                $route->setDefaultOptions( $options );
                $data[] = sprintf( '$this->routes[\'%s\'] = unserialize(\'%s\');', $name, serialize( $route ) );
            }
        }

        return sprintf(
            "<?php\n// auto-generated by dinRoutingConfigHandler\n// date: %s\n%s\n",
            date( 'Y/m/d H:i:s' ), implode( "\n", $data )
        );

    } // dinRoutingConfigHandler::execute()

} // dinRoutingConfigHandler

//EOF